### PR TITLE
Dev v0.1

### PR DESCRIPTION
**Pull request by generationmake**
merge branch dev_v0.1 to create first release of PCB

### CODE REVIEW

**Comment by generationmake** [comment]
todo:
check type and size of spacers
add mounting holes
do layout

**Comment by aentinger** [comment]
Nice work :+1:

**Comment by generationmake** [comment]
@aentinger can you check if all the pins used for the OV2640 module in the schematic are free in the FPGA?
Is there anything else to improve or document?

**Comment by aentinger** [comment]
Great work @generationmake 👍 I'll perform a review on the schematic and will get back to you 😉

**Comment by generationmake** [comment]
@aentinger you can also check the I2C situation. I haven't found a solution to connect I2C to the Mini PCIe connector. We could connect it to the "additional I2C port" or to the baseboard.
There might also be a collision with the micro HDMI connector. But I think we won't need it on the copter but maybe for debugging.

**Comment by generationmake** [comment]
and if we need pull ups on I2C or any other line (like reset).

**Comment by generationmake** [comment]
Hi @aentinger  
i added the pull ups and leds. I also moved the camera connector to onblock the HDMI connector on the Vidor 4000. 
Documentation with labels on PCB and in schematic are still missing.
But you can already check if the rest is how you intended.

**Comment by aentinger** [comment]
Good Morning @generationmake :wave: 
First of all let me say that the adapter looks great - good work 👍. Here are a couple of things that came to my attention when looking through the files:

- Regarding the LEDs on the the I2C bus lines SCL and SDA: Since I2C is usually open-collector driven I wonder who should provide the current to drive the LEDs? Is it possible that we might need a buffer amplifier circuit to drive the LEDs? 
- Regarding the I2C-Pull-Up-Resistors: I'd suggest to connect them via solder jumpers to SDA/SCL because I'm not yet clear if we need those pull-up-R's at all. What do you think?

**Comment by generationmake** [comment]
Hi @aentinger 
You are right. I will add buffers for the LEDs on the I2C lines and solder jumpers for the pull ups. 
Stay tuned. ;-)

**Comment by aentinger** [comment]
Good Morning @generationmake :wave: I believe you added the I2C pull-up solder jumpers as well as the buffer amplifiers because I can see them in the 3D rendering. However, it seems to me that you did not update **VidorCameraAdapter_schematic.pdf**. Therefore I can not yet clear the design for production and would ask you to update the PDF schematic file as well 😉

**Comment by aentinger** [comment]
I've come another small correction: Since `PCLK` is generated by the OV2640 module and the output of the pixel data is synched to it it makes sense to connect `PCLK` to a clock input of the FPGA. I therefore suggest to
* connect `PCLK` with `PEX_PIN25` (**CLK13_B4_R9/DIFFCLK_7P**)
* connect `XCLK` with `PEX_PIN23` (**CLK12_B4_T9/DIFFCLK_7N**)
(Basically swap PCLK and XCLK on the connector).

**Comment by aentinger** [comment]
Hi :wave: and another small correction: `LED_G` and `LED_B` are connected to Pin #17/19 which are part of the WiFi Nina module. Pin #6/8/10/12 are still free.

**Comment by generationmake** [comment]
Hi @aentinger I added all changes as you requested. I also added pdfs with the schematic and assembly.

**Comment by generationmake** [comment]
The code generation for the FPGA brought new findings regarding the pinning of the MiniPCIe connector: https://github.com/107-systems/viper-vidor-fpga/blob/master/syn/MKR-Vidor-4000-Viper-Quadcopter-Pins.qsf#L132:L156
Pinning needs to be changed!

**Comment by aentinger** [comment]
All good, therefore I'm merging this PR 👍

**Pull request merged**
